### ISSUE TITLE
IsClientAFK (bool)

### ISSUE THREAD

**Issue by Cruze03** [MitchDizzle/AFKManager#1]
Can you create this native? Good plugin btw 😁

**Comment by Cruze03** [comment]
and add `AFK_DoNothing` too if possible!

**Comment by MitchDizzle** [comment]
`AFK_DoNothing`
I'm curious on how this would be used.

**Comment by Cruze03** [comment]
Ummm, I just want this plugin to detect afk player and do nothing. So that we can give credits only to active players. No need to warn/punish afk player!

**Comment by MitchDizzle** [comment]
Are you on the `dev` branch version? If you are you can disable the automated kicking and stuff. The AFK_* defines are for when you use the menu atleast. I'm okay with adding the native part of the request.

**Comment by Cruze03** [comment]
Oh, okay my bad 😅😆. and Thanks ♥️

**Comment by MitchDizzle** [comment]
I did some updates to https://github.com/MitchDizzle/AFKManager/tree/dev
last week, added a native to get how long a player has been afk.

**Comment by Cruze03** [comment]
Thank you kind sir. Working good! ❤️
